<!-- 2024-01-01 "Refactor `design/head/includes` scripts to a Magento module": https://github.com/cabinetsbay/core/issues/1 -->
<script>
window.dataLayer = window.dataLayer || [];
</script>
<!-- Start of Zendesk Widget script -->
<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=d788c408-e1a5-470a-8863-5e48621b2fba"> </script>
<!-- End of Zendesk Widget script -->
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '203719850981922');
fbq('track', 'PageView');
</script>
<noscript>
 <img height="1" width="1"
src="https://www.facebook.com/tr?id=203719850981922&ev=PageView
&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
<style>
.wp_newsletter_trigger_button {z-index:8000;right:-50px}
.cms-home .wp_newsletter_trigger_button{right:0}
.block.block-search{display:none !important;}
@media screen and (max-width: 680px) {.page-footer .block.newsletter .form.subscribe {display: block;overflow: hidden;}}
#cabinet-assembly img, #specifications img {height: auto !important;}
.grecaptcha-badge {bottom: 75px !important;}
.old-price, .old.price {
  text-decoration: none !important;
}
.old-price .price {
text-decoration: line-through;
}
</style>
<meta name="google-site-verification" content="2MU7dvnQiQdpm1burH8qfTUyBMJeO0pRgLbmrH9EWHE" />
<!-- 2024-01-01 "«jQuery is not defined» on my workstation": https://github.com/cabinetsbay/site/issues/53 -->
<?= df_js('CabinetsBay_Core'); ?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MDDHKRG');</script>
<!-- End Google Tag Manager -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-8NXSJEWV17"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-8NXSJEWV17');
</script>
<script>
	// 2024-04-05 https://docs.affirm.com/payments/docs/afjs-reference
	_affirm_config = {
		public_api_key: "AB386TRIY90ATCSD",
		script: "https://cdn1.affirm.com/js/v2/affirm.js"
	};
	// 2024-04-05
	// "«Mismatched anonymous define() module» on loading `cdn1.affirm.com/products/affirmjs/master/dist/ldclient.min.js`"
	// https://github.com/cabinetsbay/site/issues/128
	require(['domReady!'], () => {
		debugger;
		setTimeout(() => {
			(() => {
				var d;
				var affirm = window['affirm'] || {};
				var n = document.getElementsByTagName('script')[0];
				var k = function(a, b, c) {return function(){a[b]._.push([c, arguments])}};
				affirm['checkout'] = k(affirm, 'checkout', "set");
				d = affirm['checkout'];
				affirm['ui'] = {};
				affirm['ui']._ = [];
				d._ = [];
				affirm['ui']['ready'] = k(affirm, 'ui', 'ready');
				a = 0;
				for (
					b = "set add save post open empty reset on off trigger ready setProduct".split(" ");
					a < b.length;
					a++
				) {
					d[b[a]] = k(affirm, 'checkout', b[a]);
				}
				a = 0;
				for (
					b = ["get", "token", "url", "items"];
					a < b.length;
					a++
				) {
					d[b[a]] = function(){};
				}
				var script = document.createElement('script');
				script.async = !0;
				script.src = _affirm_config['script'];
				n.parentNode.insertBefore(script, n);
				delete _affirm_config[f];
				d(_affirm_config);
				window['affirm'] = affirm;
			})();
			affirm.ui.ready(() => {
				var a = {"page_type":"home", "mode":"modal"};
				affirm.prequal.set(a);
			});
		}, 1000);
	});
</script>