<?php
# 2024-05-06
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Theme/templates/homepage.phtml`":
# https://github.com/cabinetsbay/core/issues/8
use Magento\Framework\View\Element\Template as B;
/** @var B $block */ $b = $block; /** @var B $b */
?>
<div class="homepage-grid">
	<?= df_cms_block('home-page-slider') ?>
	<div class="homepage-why-us">
		<?= df_cc_n(df_cms_block('home-page-why-us'), df_cms_block('home-page-why-us-icon-block')) ?>
	</div>
	<?= df_block_output('CabinetsBay_Catalog', 'popular') ?>
	<div class="homepage-workflow"><?= df_cms_block('home-page-project-workflow') ?></div>
	<div class="homepage-affirm-banner">
		<a href="/financing.html"><img src="<?= $b->getViewFileUrl('images/affirm_banner.svg') ?>"/></a>
	</div>
	<div class="homepage-affirm-banner-mobile">
		<a href="/financing.html"><img src="<?= $b->getViewFileUrl('images/affirm_banner_mob.svg') ?>"/></a>
	</div>
	<div class="homepage-call-us">
		<div class="left">
			<div class="call-us-block">
				<h4>Call Us Today</h4>
				<h4><?= trim(strip_tags(df_cms_block('block-header-top-phone'), '<a>')) ?></h4>
			</div>
			<div><?= trim(strip_tags(df_cms_block('home-page-schedule'), '<br>')) ?></div>
		</div>
		<div class="right">
			<div class="catalog-links">
				<div><?= trim(strip_tags(df_cms_block('home-page-catalog-links'), '<a><ul><li>')) ?></div>
			</div>
		</div>
	</div>
</div>