<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
# 2024-03-25
# These tabs are visible on wide screens only.
echo df_tag('ul', 'category-menu', df_map_k(function($k, $v):string {return df_tag('li', ['data-role' => 'title'],
	df_tag('a', [
		# 2024-03-25
		# "The contents of the tabs «Product Overview», «Specifications», «Cabinet Assembly», «Matching Styles»
		# should be always visible": https://github.com/cabinetsbay/site/issues/120
		'class' => 'scrollTo'
		,'href' => "#$k"
	], $v)
);}, [
	'overview' => 'Product Overview'
	,'specifications' => 'Specifications'
	,'cabinet-assembly' => 'Cabinet Assembly'
	,'matching-styles' => 'Matching Styles'
]));
?>
<div id='overview' class='category-tab' data-role='content'>
	<label>Product Overview <span class='submenu-toggle' data-role='trigger' tabindex='0'></span></label>
	<div class='content'>
		<?= df_block_output('CabinetsBay_Core', 'catalog/category/tabs/overview', ['b' => $b]) ?>
	</div>
</div>
<div id="specifications" class="category-tab category-tab-specifications" data-role="content">
	<label>Specifications <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?= $b->l3a('cb_specs') ?>
	</div>
</div>
<div id="cabinet-assembly" class="category-tab" data-role="content">
	<label>Cabinet Assembly <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?= $b->l3a('cb_assembly') ?>
	</div>
</div>
<div id="matching-styles" class="category-tab" data-role="content">
	<label>Matching Styles <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?php /** @var \Magento\Catalog\Helper\Category $ch */
		$ch = df_category_h(); ?>
		<?= $b->l3a('cb_styles') ?>
		<?php $cc = $b->l3p(); ?>
		<?php if(count($cc) > 0) :
		  print '<div class="c-products-grid">';
		  print '<ul>';
		  foreach ($cc as $c) {/** @var C $c */
			print '<li>';
			print '<a href="' . $ch->getCategoryUrl($c) . '">';
			print '<div>' . $c->getName() . '</div>';
			if ($c->getData('cb_kitchen_set') != '') {
				print
					'<div class="size-price"><b>'
					. $c->getData('cb_kitchen_set')
					. '</b>'
					. $c->getData('cb_kitchen_price')
					. '</div>'
				;
			}
			try {
				print '<img src="' . $c->getImageUrl() . '" border="0" />';
			}
			catch (\Magento\Framework\Exception\LocalizedException $e) {}
			print '</a>';
			print
				'<div><a href="'
				. $ch->getCategoryUrl($c)
			  	. '">Shop cabinets</a><a href="'.$c->getData('cb_door_sample_link').'">Order sample</a></div>';
			print '</li>';
		  }
		  print '</ul>';
		  print '</div>';
		endif; ?>
	</div>
</div>