<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */ /** @var string $title */
# 2024-03-25
# These tabs are visible on wide screens only.
echo df_tag('ul', 'category-menu', df_map_k(function($k, $v):string {return df_tag('li', ['data-role' => 'title'],
	df_tag('a', [
		# 2024-03-25
		# "The contents of the tabs «Product Overview», «Specifications», «Cabinet Assembly», «Matching Styles»
		# should be always visible": https://github.com/cabinetsbay/site/issues/120
		'class' => 'scrollTo'
		,'href' => "#$k"
	], $v)
);}, [
	'overview' => 'Product Overview'
	,'specifications' => 'Specifications'
	,'cabinet-assembly' => 'Cabinet Assembly'
	,'matching-styles' => 'Matching Styles'
]));
df_assert($l3 = $b->l3()); /** @var C $l3 */
?>
<div id='overview' class='category-tab' data-role='content'>
	<label>Product Overview <span class='submenu-toggle' data-role='trigger' tabindex='0'></span></label>
	<div class='content'>
		<?= $title # 2024-03-11 It is visible on wide screens only ?>
		<div class='category-info'>
			<div class='category-tab-left'>
				<?php if ($ii = $b->images()) { ?>
					<ul id='category-gallery' class='gallery list-unstyled cS-hidden'>
						<?=
							df_cc_n(df_map_k($ii, function(string $f, string $t):string {return
								df_tag('li', [
									'data-src' => $u = df_media_path2url("wysiwyg/catalog-carousel-images/$f")
									,'data-thumb' => $u
								], df_tag('img', ['alt' => $t,'src' => $u, 'title' => $t]))
							;}))
						?>
					</ul>
					<script>
						require(['jquery', 'domReady!'], function($) {
							let totalWidth = 0;
							$('.owl-thumb-item').each(function() {
								totalWidth += parseInt($(this).width(), 10);
							});
							$('.owl-thumbs').css('width', (totalWidth + 20)+'px');
						});
					</script>
				<?php }
				else {
					try {
						if ($url = $l3->getImageUrl()) {
							echo df_catalog_output()->categoryAttribute(
								$l3
								,df_tag('div', 'category-image', df_tag('img', [
									'alt' => $l3->getName()
									,'class' => 'image'
									,'src' => $url
									,'title' => $l3->getName()
								]))
								,'image'
							);
						}
					} catch (\Magento\Framework\Exception\LocalizedException $e) {}
				}
				?>
			</div>
			<div class="category-tab-right">
				<?php if ($_description = $l3->getDescription()): ?>
					<div class="category-description">
						<?= df_catalog_output()->categoryAttribute($l3, $_description, 'description') ?>
					</div>
				<?php endif; ?>
				<div class="category-subdescription">
					<div class="table-view">
						<a href="/sample-doors.html">Order Sample</a>
						<a href="/kitchen-design-assistance.html">Free Design</a>
					</div>
					<a class="scrollTo" href="#layer-product-list">Shop Cabinets Below <i></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="specifications" class="category-tab category-tab-specifications" data-role="content">
	<label>Specifications <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?= $b->l3a('cb_specs') ?>
	</div>
</div>
<div id="cabinet-assembly" class="category-tab" data-role="content">
	<label>Cabinet Assembly <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?= $b->l3a('cb_assembly') ?>
	</div>
</div>
<div id="matching-styles" class="category-tab" data-role="content">
	<label>Matching Styles <span class="submenu-toggle" data-role="trigger" tabindex="0"></span></label>
	<div class="content">
		<?php /** @var \Magento\Catalog\Helper\Category $ch */
		$ch = df_category_h(); ?>
		<?= $b->l3a('cb_styles') ?>
		<?php $cc = $b->l3p(); ?>
		<?php if(count($cc) > 0) :
		  print '<div class="c-products-grid">';
		  print '<ul>';
		  foreach ($cc as $c) {/** @var C $c */
			print '<li>';
			print '<a href="' . $ch->getCategoryUrl($c) . '">';
			print '<div>' . $c->getName() . '</div>';
			if ($c->getData('cb_kitchen_set') != '') {
				print
					'<div class="size-price"><b>'
					. $c->getData('cb_kitchen_set')
					. '</b>'
					. $c->getData('cb_kitchen_price')
					. '</div>'
				;
			}
			try {
				print '<img src="' . $c->getImageUrl() . '" border="0" />';
			}
			catch (\Magento\Framework\Exception\LocalizedException $e) {}
			print '</a>';
			print
				'<div><a href="'
				. $ch->getCategoryUrl($c)
			  	. '">Shop cabinets</a><a href="'.$c->getData('cb_door_sample_link').'">Order sample</a></div>';
			print '</li>';
		  }
		  print '</ul>';
		  print '</div>';
		endif; ?>
	</div>
</div>