<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
echo $b->l3a('cb_styles');
$cc = $b->l3p();
if (count($cc)) {
  print '<div class="c-products-grid">';
  print '<ul>';
  foreach ($cc as $c) {/** @var C $c */
	print '<li>';
	print '<a href="' . $c->getUrl() . '">';
	print '<div>' . $c->getName() . '</div>';
	if ($c->getData('cb_kitchen_set') != '') {
		print
			'<div class="size-price"><b>'
			. $c->getData('cb_kitchen_set')
			. '</b>'
			. $c->getData('cb_kitchen_price')
			. '</div>'
		;
	}
	try {
		print '<img src="' . $c->getImageUrl() . '" border="0" />';
	}
	catch (\Magento\Framework\Exception\LocalizedException $e) {}
	print '</a>';
	print
		'<div><a href="'
		. $c->getUrl()
		. '">Shop cabinets</a><a href="'.$c->getData('cb_door_sample_link').'">Order sample</a></div>';
	print '</li>';
  }
  print '</ul>';
  print '</div>';
}