<?php
# 2024-03-25
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
echo $b->l3a('cb_styles');
if (count($cc = $b->l3p())) { /** @var C[] $cc */ ?>
	<div class='c-products-grid'>
		<ul>
			<?php foreach ($cc as $c) {/** @var C $c */ ?>
				<li>
					<a href='<?= $c->getUrl() ?>'>
						<div><?= $c->getName() ?></div>
						<?php if ($ks = $c['cb_kitchen_set']) { ?>
							<div class='size-price'>
								<b><?= $ks ?></b><?= $c['cb_kitchen_price'] ?>
							</div>
						<?php } ?>
						<img border='0' src='<?= $c->getImageUrl() ?>'/>
					</a>
					<div>
						<a href='<?= $c->getUrl() ?>'>Shop cabinets</a>
						<a href='<?= $c['cb_door_sample_link'] ?>'>Order sample</a>
					</div>
				</li>
			<?php } ?>
		</ul>
	</div>
	<?php
}