<?php
# 2024-04-26
# "The `checkout/cart` page should show prices before and after discounts (similar to the mini cart)":
# https://github.com/cabinetsbay/site/issues/143
use Magento\Tax\Block\Item\Price\Renderer as B;
/** @var B $block */ $b = $block; /** @var B $b */
$_item = $b->getItem();
?>
<?php if (($b->displayPriceInclTax() || $b->displayBothPrices()) && !$_item->getNoSubtotal()) : ?>
    <span class="price-including-tax" data-label="<?= $b->escapeHtmlAttr(__('Incl. Tax')) ?>">
        <span class="cart-price">
            <?= /* @noEscape */ $b->formatPrice($_item->getRowTotalInclTax()) ?>
        </span>
    </span>
<?php endif; ?>

<?php if (($b->displayPriceExclTax() || $b->displayBothPrices()) && !$_item->getNoSubtotal()) : ?>
    <span class="price-excluding-tax" data-label="<?= $b->escapeHtmlAttr(__('Excl. Tax')) ?>">
        <span class="cart-price">
            <?= /* @noEscape */ $b->formatPrice($_item->getRowTotal()) ?>
        </span>
    </span>
<?php endif; ?>
