<?php
# 2024-04-26
# "The `checkout/cart` page should show prices before and after discounts (similar to the mini cart)":
# https://github.com/cabinetsbay/site/issues/143
use Magento\Catalog\Model\Product as P;
use Magento\Quote\Model\Quote\Item as I;
use Magento\Tax\Block\Item\Price\Renderer as B;
/** @var B $block */ $b = $block; /** @var B $b */
$i = $b->getItem(); /** @var I $i */
$p = $i->getProduct(); /** @var P $p */
$new = $p->getFinalPrice(); /** @var string $new */
$old = $p->getPrice(); /** @var string $old */
$hasDiscount = $old !== $new; /** @var bool $hasDiscount */
?>
<span class='price-excluding-tax' data-label='Excl. Tax'>
	<?=
		df_cc_n(
			df_tag('span', df_cc_s('cart-price', !$hasDiscount ? '' : 'final-price'), $b->formatPrice($new))
			,!$hasDiscount ? '' : df_tag('span', 'minicart-old-price', $b->formatPrice($old))
		)
	?>
</span>