<?php
# 2024-03-15
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/site/issues/112
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
if ($b->isRTA()) {
  print '<div id="faq-purchase" class="product-page-faq">';
  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-faq-rta-welcome')->toHtml(), '<p><h3>');
  print '</div>';
  print '<div class="product-page-faq">';
  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-faq-rta-body')->toHtml(), '<p><h4><strong>');
  print '</div>';
  print '<div id="how-to-shop" class="product-page-how-to-shop mobile-view">';
  print strip_tags($b
					 ->getLayout()
					 ->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-rta-how-to-shop')
					 ->toHtml(), '<p><h3>');
  print '<a href="#products_list" class="scrollTo">Click here to start shopping</a>';
  print '</div>';
  print '<div class="product-page-info mobile-view">';
  print strip_tags($b
					 ->getLayout()
					 ->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-rta-info')
					 ->toHtml(), '<p><strong><a><table><tbody><tr><td><h3>');
  print '</div>';
}
elseif ($b->isPA()) { // If pre-assembled products
  print '<div id="faq-purchase" class="product-page-faq">';
  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-faq-pa-welcome')->toHtml(), '<p><h3>');
  print '</div>';
  print '<div class="product-page-faq">';
  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-faq-pa-body')->toHtml(), '<p><h4><strong>');
  print '</div>';
  print '<div id="how-to-shop" class="product-page-how-to-shop mobile-view">';
  print strip_tags($b
					 ->getLayout()
					 ->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-pa-how-to-shop')
					 ->toHtml(), '<p><h3>');
  print '<a href="#products_list" class="scrollTo">Click here to start shopping</a>';
  print '</div>';
  print '<div class="product-page-info mobile-view">';
  print strip_tags($b
					 ->getLayout()
					 ->createBlock('Magento\Cms\Block\Block')
					 ->setBlockId('product-page-pa-info')
					 ->toHtml(), '<p><strong><a><table><tbody><tr><td><h3>');
  print '</div>';
}