<?php
# 2024-03-14
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/site/issues/112
use Magento\Catalog\Helper\Category as H;
use Magento\Catalog\Model\Category as C;
use Magento\Catalog\Model\ResourceModel\Category\Collection as CC;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $b */
$h = df_category_h(); /** @var H $h */
$products = '';
$filterStyle = $filterConstruction = ['all' => '<li data-style="all">All</li>'];
$cc = df_category_children($b->getCurrentCategory())->setOrder('position', 'ASC'); /** @var CC $cc */
foreach ($cc as $c) {/** @var C $c */
	$filterStyle[$c->getData('cb_kitchen_style')] =
	  '<li data-style="'.$c->getData('cb_kitchen_style').'">'.$c->getData('cb_kitchen_style').'</li>';

	$filterConstruction[$c->getData('cb_kitchen_type')] =
	  '<li data-style="'.$c->getData('cb_kitchen_type').'">'.$c->getData('cb_kitchen_type').'</li>';

	/** @var \Magento\Catalog\Model\Category\Interceptor $c */
	$products.= '<li data-sorterprice="'.preg_replace('/[^0-9.]+/', '', $c->getData('cb_kitchen_price')).'" data-sortercolor="'.$c->getData('cb_kitchen_color').'" data-sorterstyle="'.$c->getData('cb_kitchen_style').'" data-sorterconstruction="'.$c->getData('cb_kitchen_type').'">';
	$products.= '<a href="'
				  . $h->getCategoryUrl($c)
				  . '">';
	$products.= '<div>' . $c->getName() . '</div>';
				if ($c->getData('cb_kitchen_set') != '') {
				  $products.= '<div class="size-price"><b>' . $c->getData('cb_kitchen_set') . '</b>'
				  . $c->getData('cb_kitchen_price') . '</div>';
				}
				try {
				  $products.= '<img src="' . $c->getImageUrl() . '" border="0" />';
				} catch (\Magento\Framework\Exception\LocalizedException $e) {

				}
	$products.= '</a>';
	$products.= '<div><a href="'
				  . $h->getCategoryUrl($c)
				  . '">Shop cabinets</a><a href="'.$c->getData('cb_door_sample_link').'">Order sample</a></div>';
	$products.= '</li>';
}
?>
<div class="category-filterblock short-first">
	<div>
		<label>Filter</label>
	</div>
	<div>
		<div id="dropdown-price" class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
			<span class="action toggle" data-toggle="dropdown" aria-haspopup="true">
				<span>Price</span>
			</span>
			<ul class="dropdown">
				<li data-sortby="asc">Low-High</li>
				<li data-sortby="desc">High-Low</li>
			</ul>
		</div>
	</div>
	<div>
		<div id="dropdown-color" class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
			<span class="action toggle" data-toggle="dropdown" aria-haspopup="true">
				<span>Color</span>
			</span>
			<ul class="dropdown">
				<li data-sortby="lighter">Lighter</li>
				<li data-sortby="darker">Darker</li>
			</ul>
		</div>
	</div>
	<div>
		<div id="dropdown-style" class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
			<span class="action toggle" data-toggle="dropdown" aria-haspopup="true">
				<span>Style (All)</span>
			</span>
			<ul class="dropdown">
				<?= implode("", $filterStyle) ?>
			</ul>
		</div>
	</div>
	<div>
		<div id="dropdown-construction" class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
			<span class="action toggle" data-toggle="dropdown" aria-haspopup="true">
				<span>Cabinet Construction (All)</span>
			</span>
			<ul class="dropdown"><?= implode("", $filterConstruction); ?></ul>
		</div>
	</div>
</div>
<?php if (!empty($products)) {
	?><div class="c-products-grid"><ul id="products_list"><?= $products ?></ul></div><?php
}